### ISSUE TITLE
Improved agent name detection

### ISSUE THREAD

**Issue by cwestbye** [bvenable/ingressocr#2]
I was finding that the parsed agent name had trailing characters (probably from the share icon). Changing line 11 of the ingressocr script to truncate characters after the first space resolved this for me:

INGRESSUSER=$(grep -A2 AGENT $TEMPFILE | fgrep -v "LVL" | egrep "[a-z]" | tail -1 | cut -d' ' -f1)

**Comment by bvenable** [comment]
We've made some improvements in this area using grayscale. Mostly it's an issue with the underlying OCR engine. I've looked into other engines but haven't yet found one that is perfect or even markedly better overall.
