### ISSUE TITLE
Frequently reads a 6 for an 8

### ISSUE THREAD

**Issue by interpotential** [bvenable/ingressocr#4]
When feeding it a screenshot of my agent stats made on an Xperia Z, ingressocr (or actually, the underlying tesseract) frequently reads an 8 there where the correct number is 6.

However, when I cut out the number that is read wrongly and feed that to tesseract directly it is read correctly. 

Attached is a full screenshot of my agent stats, as well as the cropped out number (in this case: deployed resonators)
![20-694](https://cloud.githubusercontent.com/assets/123354/4702604/592ccf8a-5864-11e4-9655-60cbfcfc6ed6.png)
![profile_20141020_154825_0](https://cloud.githubusercontent.com/assets/123354/4702621/7f1aa636-5864-11e4-90bf-2fd687335723.png)

**Comment by bvenable** [comment]
This should be fixed using grayscale. It's more an issue with the underlying OCR engine when it happens. I've looked into other OCR engines but haven't yet found one that is perfect.
